title: "My Portfolio"
description: "Showcasing my coding and hardware projects"
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-include-cache

# Navigation
nav:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "About"
    url: /about/
